import math

# Paths
VOCABULARY_FILE = 'vocab.txt'
VIDEOS_DIR = 'npy_videos'
ANNOTATIONS_DIR = 'npy_alignments'

# General
SEQUENCE_IN_MAX_LEN = 80
SEQUENCE_OUT_MAX_LEN = 16

# Backbone hyperparameters
CONV_LAYERS_TO_FREEZE = 6

# Transformer hyperparametes
TRANSFORMER_D_MODEL = 128
TRANSFORMER_N_HEADS = 4
TRANSFORMER_ENCODER_LAYERS = 6
TRANSFORMER_DECODER_LAYERS = 2
TRANSFORMER_DIM_FEEDFORWARD = 256
TRANSFORMER_DROPOUT = 0.1

# Training
INITIAL_BATCH_SIZE = 1
EPOCHS = 1
INCREASE_DIFFICULTY_ITERS = 200
MAX_INCREASES = math.ceil(math.log2(SEQUENCE_OUT_MAX_LEN/INITIAL_BATCH_SIZE))